AWSTemplateFormatVersion: 2010-09-09
Resources:
  CodeBuildServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: Root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudWatchLogsPolicy
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
              - Sid: S3GetObjectPolicy
                Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                Resource: '*'
              - Sid: S3PutObjectPolicy
                Effect: Allow
                Action:
                  - 's3:PutObject'
                Resource: '*'
              - Sid: S3BucketIdentity
                Effect: Allow
                Action:
                  - 's3:GetBucketAcl'
                  - 's3:GetBucketLocation'
                Resource: '*'
  CodeBuildSourceCredential:
    Type: AWS::CodeBuild::SourceCredential
    Properties:
        AuthType: PERSONAL_ACCESS_TOKEN
        ServerType: GITHUB
        Toke: "{{resolve:secretmanager:GITHUB_ACCESS:SecretScript:GITHUB_ACCESS_TOKEN}}"
    
  CodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Ref 'AWS::StockName'
      ServiceRole: !Ref CodeBuildServiceRole.Arn
      Source: !Ref CodeBuildSourceCredential
        Type:GITHUB
        Location: https://github.com/MohammadTAE/github-aws-cicd.git
        BuildSpec: buildspec.yml
        Auth:
            Type: OAUTH
            Resource: SourceCredetial
        Artifacts:
        Type: NO_ARTIFACTS
      Triggers:
        Webhook: true
        FilterGroups:
            --Type: Event
              Pattern: PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED
             -Type: BASE_REF
              Pattern: !Sub ^refs/heads/main$
        

